### ISSUE TITLE
Fix liburi-perl dependency

### ISSUE THREAD

**Issue by subogero** [subogero/u2b#1]
It's listed falsely as `liburi-escape-perl`.

**Comment by subogero** [comment]
Deb package version 0.2-1 will be uploaded soon to package repo.

**Comment by subogero** [comment]
Done.

**Comment by pablo375** [comment]
Thanks! I could install remotepi without problems. I have an additional question: In order to play YouTube videos do I have to paste a link into the "Search YouTube field" or the input is a keyword? Because I get nothing.

Again thanks for your support!

**Comment by subogero** [comment]
The input is a keyword or a list of keywords. It can be the 11-character video id as well. If it fails, try to reload the app in the browser. I've seen the unresponsive YouTube search sometimes, I'll try to debug it.
